/*
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 * SPDX-License-Identifier: Apache-2.0
 */
package aws.sdk.kotlin.hll.dynamodbmapper.codegen.annotations.rendering

import aws.sdk.kotlin.hll.codegen.model.*
import aws.sdk.kotlin.hll.codegen.rendering.BuilderRenderer
import aws.sdk.kotlin.hll.codegen.rendering.RenderContext
import aws.sdk.kotlin.hll.codegen.rendering.RendererBase
import aws.sdk.kotlin.hll.codegen.util.generatedAnnotation
import aws.sdk.kotlin.hll.codegen.util.plus
import aws.sdk.kotlin.hll.codegen.util.visibility
import aws.sdk.kotlin.hll.dynamodbmapper.*
import aws.sdk.kotlin.hll.dynamodbmapper.codegen.annotations.AnnotationsProcessorOptions
import aws.sdk.kotlin.hll.dynamodbmapper.codegen.annotations.DestinationPackage
import aws.sdk.kotlin.hll.dynamodbmapper.codegen.annotations.GenerateBuilderClasses
import aws.sdk.kotlin.hll.dynamodbmapper.codegen.model.MapperTypes
import aws.sdk.kotlin.hll.dynamodbmapper.items.AutoGeneratedConverter
import aws.smithy.kotlin.codegen.core.RuntimeTypes
import aws.smithy.kotlin.runtime.collections.get
import com.google.devtools.ksp.KspExperimental
import com.google.devtools.ksp.getAnnotationsByType
import com.google.devtools.ksp.getConstructors
import com.google.devtools.ksp.isAnnotationPresent
import com.google.devtools.ksp.symbol.*

/**
 * Renders the classes and objects required to make a class usable with the DynamoDbMapper such as schemas, builders, and converters.
 * @param classDeclaration the [KSClassDeclaration] of the class
 * @param ctx the [RenderContext] of the renderer
 */
@OptIn(KspExperimental::class)
internal class SchemaRenderer(
    private val classDeclaration: KSClassDeclaration,
    private val ctx: RenderContext,
) : RendererBase(ctx, "${classDeclaration.qualifiedName!!.getShortName()}Schema") {
    private val className = classDeclaration.qualifiedName!!.getShortName()
    private val classStructure = Structure.from(classDeclaration)
    private val classType = Type.from(classDeclaration)

    private val builderName = "${className}Builder"
    private val converterName = "${className}Converter"
    private val schemaName = "${className}Schema"

    private val shouldRenderItemConverter: Boolean
    private val itemConverter: Type

    /**
     * Whether the annotated type is a table item ([DynamoDbItem]) as opposed to a nested-only mappable type
     * ([DynamoDbMappable]). Table items enforce primary key requirements and generate a schema + table accessor;
     * nested types generate only converters.
     */
    private val isTableItem = classDeclaration.isAnnotationPresent(DynamoDbItem::class)

    private val properties = classDeclaration.getMappedProperties()

    private val partitionKeyProps = properties.filter { it.isPk }
    private val sortKeyProps = properties.filter { it.isSk }

    private val partitionKeyTypeRefs = partitionKeyProps.map { it.typeRef }
    private val sortKeyTypeRefs = sortKeyProps.map { it.typeRef }

    /**
     * Skip rendering a class builder if:
     *   - the user has configured GenerateBuilders to WHEN_REQUIRED (default value) AND
     *   - the class has all mutable members AND
     *   - the class has a zero-arg constructor
     */
    private val shouldRenderBuilder: Boolean = run {
        val alwaysGenerateBuilders = ctx.attributes[AnnotationsProcessorOptions.GenerateBuilderClassesAttribute] == GenerateBuilderClasses.ALWAYS
        val hasAllMutableMembers = properties.all { it.isMutable }
        val hasZeroArgConstructor = classDeclaration.getConstructors().any { constructor -> constructor.parameters.all { it.hasDefault } }

        !(!alwaysGenerateBuilders && hasAllMutableMembers && hasZeroArgConstructor)
    }

    init {
        // @DynamoDbMappable targets ANNOTATION_CLASS so it can meta-annotate @DynamoDbItem, which means the Kotlin
        // compiler alone won't stop a user from incorrectly applying it to their own annotation class. Fail fast with a
        // located diagnostic in that case.
        if (classDeclaration.classKind == ClassKind.ANNOTATION_CLASS) {
            val msg = "@DynamoDbMappable cannot be applied to annotation classes " +
                "(${classDeclaration.qualifiedName?.asString()}); it is only valid on regular or data classes."
            ctx.logger.error(msg, classDeclaration)
            error(msg)
        }

        // Read the user-specified converter (if any) from whichever marker annotation applies to this type.
        val markerQualifiedName = if (isTableItem) {
            DynamoDbItem::class.qualifiedName
        } else {
            DynamoDbMappable::class.qualifiedName
        }

        val specifiedItemConverter = classDeclaration
            .annotations
            .firstOrNull { it.annotationType.resolve().declaration.qualifiedName?.asString() == markerQualifiedName }
            ?.arguments
            ?.singleOrNull()
            ?.value
            ?.let { it as KSType }
            ?.takeUnless { it.declaration.qualifiedName!!.asString() == AutoGeneratedConverter::class.qualifiedName }

        shouldRenderItemConverter = specifiedItemConverter == null

        itemConverter = specifiedItemConverter?.let(Type::from) ?: TypeRef(ctx.pkg, converterName)
    }

    override fun generate() {
        if (isTableItem) {
            validateTableItemKeys()
        } else {
            validateNestedItem()
        }

        if (shouldRenderBuilder) {
            renderBuilder()
        }

        if (shouldRenderItemConverter) {
            renderItemConverter()
        }

        if (ctx.attributes[SchemaAttributes.ShouldRenderValueConverterAttribute]) {
            renderValueConverter()
        }

        if (isTableItem) {
            renderSchema()

            if (ctx.attributes[AnnotationsProcessorOptions.GenerateGetTableMethodAttribute]) {
                renderGetTable()
            }
        }
    }

    /**
     * Validates primary key requirements for a table item ([DynamoDbItem]). Mirrors the historical fail-fast behavior:
     * exactly 1-4 partition key properties and 0-4 sort key properties.
     */
    private fun validateTableItemKeys() {
        require(partitionKeyProps.size in 1..4) {
            "Expected between 1 and 4 properties annotated with @DynamoDbPartitionKey, found ${partitionKeyProps.size}"
        }
        require(sortKeyProps.size in 0..4) {
            "Expected between 0 and 4 properties annotated with @DynamoDbSortKey, found ${sortKeyProps.size}"
        }
    }

    /**
     * Validates a nested-only mappable type ([DynamoDbMappable] without [DynamoDbItem]). Key, TTL, and counter
     * annotations are meaningful only on table items, so their presence on a nested type is a compile-time error.
     */
    private fun validateNestedItem() {
        properties.forEach { prop ->
            val invalidAnnotations = buildList {
                if (prop.isPk) add("@DynamoDbPartitionKey")
                if (prop.isSk) add("@DynamoDbSortKey")
                if (prop.isAnnotationPresent(DynamoDbTtlSeconds::class)) add("@DynamoDbTtlSeconds")
                if (prop.isAnnotationPresent(DynamoDbCounter::class)) add("@DynamoDbCounter")
            }

            if (invalidAnnotations.isNotEmpty()) {
                ctx.logger.error(
                    "Property '${prop.name}' on nested type '$className' is annotated with " +
                        "${invalidAnnotations.joinToString()}. These annotations are only valid on a @DynamoDbItem " +
                        "table item, not on a nested @DynamoDbMappable type.",
                    prop,
                )
            }
        }
    }

    private fun renderBuilder() {
        val builderCtx = ctx.copy(
            attributes = ctx.attributes + (ModelAttributes.GeneratedApi to true),
        )
        val members = properties.map(Member::from).toSet()
        BuilderRenderer(builderCtx, this, classStructure, classType, members).render()
    }

    private fun renderItemConverter() {
        generatedAnnotation()
        withBlock(
            "#Lobject #L : #T by #T(",
            ")",
            ctx.attributes.visibility,
            converterName,
            MapperTypes.Items.itemConverter(classType),
            MapperTypes.Items.SimpleItemConverter,
        ) {
            if (shouldRenderBuilder) {
                write("builderFactory = ::#L,", builderName)
                write("build = #L::build,", builderName)
            } else {
                write("builderFactory = { $className() },")
                write("build = { this },")
            }

            withBlock("descriptors = arrayOf(", "),") {
                properties.forEach {
                    renderAttributeDescriptor(it)
                }
            }
        }
        blankLine()
    }

    /**
     * Render a [ValueConverter] for the current class by wrapping the generated/user-provided [ItemConverter]
     * with our [ItemValueConverter].
     */
    private fun renderValueConverter() {
        generatedAnnotation()
        write(
            "#Lval #L: #T = #T(#T, #T)",
            ctx.attributes.visibility,
            "${className}ValueConverter",
            MapperTypes.Values.valueConverter(classType),
            HllTypes.MappingCore.Converters.ConverterChain,
            itemConverter,
            MapperTypes.Values.ItemValueConverter,
        )
        blankLine()
    }

    private fun renderAttributeDescriptor(prop: KSPropertyDeclaration) {
        ctx.logger.info("Rendering an attribute descriptor for ${prop.simpleName.asString()}")
        withBlock("#T(", "),", MapperTypes.Items.AttributeDescriptor) {
            write("#S,", prop.ddbName) // key
            write("#L,", "$className::${prop.name}") // getter

            // setter
            if (shouldRenderBuilder) {
                write("#L,", "$builderName::${prop.name}::set")
            } else {
                write("#L,", "$className::${prop.name}::set")
            }

            // converter
            // KSP requires extra work to get a class argument out of an annotation, can't just use getAnnotationsByType
            // https://slack-chats.kotlinlang.org/t/8480301/hello-again-how-do-you-get-a-kclass-out-from-an-annotation-a
            val attributeValueConverterKsType = prop
                .annotations
                .singleOrNull { it.annotationType.resolve().declaration.qualifiedName?.asString() == DynamoDbAttributeConverter::class.qualifiedName }
                ?.arguments
                ?.single()
                ?.value
                ?.let { it as KSType }

            val attributeValueConverter = attributeValueConverterKsType?.let { Type.from(it) }
            val needsCtorInvoke = attributeValueConverterKsType?.declaration?.isObject != true

            attributeValueConverter?.let {
                writeInline("#T", it)

                if (needsCtorInvoke) {
                    writeInline("()")
                }
            } ?: run {
                renderValueConverter(prop.type.resolve())
            }
            write(",")
        }
    }

    /**
     * Renders a ValueConverter for the [ksType].
     *
     * Note: The ValueConverter(s) will be rendered without a newline in order to support deep recursion.
     * Callers are responsible for adding a newline after the top-level invocation of this function.
     */
    private fun renderValueConverter(ksType: KSType) {
        val type = Type.from(ksType)

        when {
            type.nullable -> {
                writeInline("#T(", MapperTypes.Values.NullableValueConverter)
                renderValueConverter(ksType.makeNotNullable())
                writeInline(")")
            }

            ksType.isEnum -> writeInline("#T()", MapperTypes.Values.Scalars.enumValueConverter(type))

            // Nested @DynamoDbMappable / @DynamoDbItem type: reference its generated value converter.
            ksType.isUserClass -> {
                val decl = ksType.declaration

                // Multi-module nesting is out of scope for now. Declarations originating from binary dependencies have
                // no containing source file; fail fast rather than emitting a reference that won't resolve.
                if (decl.containingFile == null) {
                    ctx.logger.error(
                        "Nested type '${decl.qualifiedName?.asString()}' is defined in another module. Nesting " +
                            "@DynamoDbMappable types across modules is not yet supported; the nested type must be " +
                            "declared in the same module as the type that references it.",
                        decl,
                    )
                    return
                }

                writeInline("#T", TypeRef(nestedConverterPackage(decl), "${decl.simpleName.asString()}ValueConverter"))
            }

            type.isGenericFor(Types.Kotlin.Collections.List) -> {
                val listElementType = ksType.singleArgument()
                writeInline("#T(", MapperTypes.Values.Collections.ListValueConverter)
                renderValueConverter(listElementType)
                writeInline(")")
            }

            type.isGenericFor(Types.Kotlin.Collections.Map) -> {
                check(ksType.arguments.size == 2) { "Expected map type ${ksType.declaration.qualifiedName?.asString()} to have 2 arguments, got ${ksType.arguments.size}" }

                val (keyType, valueType) = ksType.arguments.map {
                    checkNotNull(it.type?.resolve()) { "Failed to resolved argument type for $it" }
                }

                writeInline("#T(#T, ", MapperTypes.Values.Collections.MapValueConverter, keyType.mapKeyConverter)
                renderValueConverter(valueType)
                writeInline(")")
            }

            type.isGenericFor(Types.Kotlin.Collections.Set) -> writeInline("#T", ksType.singleArgument().setValueConverter)

            else -> writeInline(
                "#T",
                when (type) {
                    Types.Smithy.Instant -> MapperTypes.Values.SmithyTypes.InstantValueConverter
                    Types.Smithy.Url -> MapperTypes.Values.SmithyTypes.UrlValueConverter
                    Types.Smithy.Document -> MapperTypes.Values.SmithyTypes.DocumentValueConverter

                    Types.Kotlin.Boolean -> MapperTypes.Values.Scalars.BooleanValueConverter
                    Types.Kotlin.String -> MapperTypes.Values.Scalars.StringValueConverter
                    Types.Kotlin.CharArray -> MapperTypes.Values.Scalars.CharArrayValueConverter
                    Types.Kotlin.Char -> MapperTypes.Values.Scalars.CharValueConverter
                    Types.Kotlin.Byte -> MapperTypes.Values.Scalars.ByteValueConverter
                    Types.Kotlin.ByteArray -> MapperTypes.Values.Scalars.ByteArrayValueConverter
                    Types.Kotlin.Short -> MapperTypes.Values.Scalars.ShortValueConverter
                    Types.Kotlin.Int -> MapperTypes.Values.Scalars.IntValueConverter
                    Types.Kotlin.Long -> MapperTypes.Values.Scalars.LongValueConverter
                    Types.Kotlin.Double -> MapperTypes.Values.Scalars.DoubleValueConverter
                    Types.Kotlin.Float -> MapperTypes.Values.Scalars.FloatValueConverter
                    Types.Kotlin.UByte -> MapperTypes.Values.Scalars.UByteValueConverter
                    Types.Kotlin.UInt -> MapperTypes.Values.Scalars.UIntValueConverter
                    Types.Kotlin.UShort -> MapperTypes.Values.Scalars.UShortValueConverter
                    Types.Kotlin.ULong -> MapperTypes.Values.Scalars.ULongValueConverter
                    else -> error(unsupportedAttributeTypeMessage(ksType, type))
                },
            )
        }
    }

    /**
     * Computes the package into which the generated value converter for a nested [decl] is emitted, matching the
     * destination-package logic used when the nested type itself is processed. This allows a nested type to live in a
     * different package than the referencing type (within the same module).
     */
    private fun nestedConverterPackage(decl: KSDeclaration): String = when (
        val dstPkg = ctx.attributes[AnnotationsProcessorOptions.DestinationPackageAttribute]
    ) {
        is DestinationPackage.Relative -> "${decl.packageName.asString()}.${dstPkg.pkg}"
        is DestinationPackage.Absolute -> dstPkg.pkg
    }

    /**
     * Builds an error message for an unsupported attribute type. When the type is a user-defined class, hints that it
     * may need a [DynamoDbMappable] annotation to be usable as a nested attribute.
     */
    private fun unsupportedAttributeTypeMessage(ksType: KSType, type: Type): String {
        val decl = ksType.declaration
        val isUserDefinedClass = (decl as? KSClassDeclaration)?.classKind == ClassKind.CLASS
        return if (isUserDefinedClass) {
            "Unsupported attribute type $type. If '${decl.qualifiedName?.asString()}' should be stored as a nested " +
                "item, annotate it with @DynamoDbMappable (or @DynamoDbItem)."
        } else {
            "Unsupported attribute type $type"
        }
    }

    private val KSType.mapKeyConverter: Type
        get() = when (val type = Type.from(this)) {
            // String
            Types.Kotlin.ByteArray -> MapperTypes.Values.Scalars.CharArrayToStringConverter
            Types.Kotlin.Char -> MapperTypes.Values.Scalars.CharToStringConverter
            Types.Kotlin.String -> MapperTypes.Values.Scalars.StringToStringConverter

            // Number
            Types.Kotlin.Byte -> MapperTypes.Values.Scalars.ByteToStringConverter
            Types.Kotlin.Double -> MapperTypes.Values.Scalars.DoubleToStringConverter
            Types.Kotlin.Float -> MapperTypes.Values.Scalars.FloatToStringConverter
            Types.Kotlin.Int -> MapperTypes.Values.Scalars.IntToStringConverter
            Types.Kotlin.Long -> MapperTypes.Values.Scalars.LongToStringConverter
            Types.Kotlin.Short -> MapperTypes.Values.Scalars.ShortToStringConverter
            Types.Kotlin.UByte -> MapperTypes.Values.Scalars.UByteToStringConverter
            Types.Kotlin.UInt -> MapperTypes.Values.Scalars.UIntToStringConverter
            Types.Kotlin.ULong -> MapperTypes.Values.Scalars.ULongToStringConverter
            Types.Kotlin.UShort -> MapperTypes.Values.Scalars.UShortToStringConverter

            // Boolean
            Types.Kotlin.Boolean -> MapperTypes.Values.Scalars.BooleanToStringConverter
            else -> error("Unsupported key type: $type")
        }

    private fun KSType.singleArgument(): KSType = checkNotNull(arguments.single().type?.resolve()) {
        "Failed to resolve single argument type for ${this.declaration.qualifiedName?.asString()}"
    }

    private val KSType.setValueConverter: Type
        get() = when (Type.from(this)) {
            Types.Kotlin.String -> MapperTypes.Values.Collections.StringSetValueConverter
            Types.Kotlin.ByteArray -> MapperTypes.Values.Collections.ByteArraySetValueConverter
            Types.Kotlin.Char -> MapperTypes.Values.Collections.CharSetValueConverter
            Types.Kotlin.CharArray -> MapperTypes.Values.Collections.CharArraySetValueConverter
            Types.Kotlin.Byte -> MapperTypes.Values.Collections.ByteSetValueConverter
            Types.Kotlin.Double -> MapperTypes.Values.Collections.DoubleSetValueConverter
            Types.Kotlin.Float -> MapperTypes.Values.Collections.FloatSetValueConverter
            Types.Kotlin.Int -> MapperTypes.Values.Collections.IntSetValueConverter
            Types.Kotlin.Long -> MapperTypes.Values.Collections.LongSetValueConverter
            Types.Kotlin.Short -> MapperTypes.Values.Collections.ShortSetValueConverter
            Types.Kotlin.UByte -> MapperTypes.Values.Collections.UByteSetValueConverter
            Types.Kotlin.UInt -> MapperTypes.Values.Collections.UIntSetValueConverter
            Types.Kotlin.ULong -> MapperTypes.Values.Collections.ULongSetValueConverter
            Types.Kotlin.UShort -> MapperTypes.Values.Collections.UShortSetValueConverter
            else -> error("Unsupported set element $this")
        }

    private fun renderSchema() {
        val schemaType = if (sortKeyProps.isEmpty()) {
            MapperTypes.Items.itemSchemaPartitionKey(classType, partitionKeyTypeRefs)
        } else {
            MapperTypes.Items.itemSchemaCompositeKey(classType, partitionKeyTypeRefs, sortKeyTypeRefs)
        }

        generatedAnnotation()
        withBlock("#Lobject #L : #T {", "}", ctx.attributes.visibility, schemaName, schemaType) {
            write("override val converter: #1T = #1T", itemConverter)

            writeInline("override val partitionKey: #T = ", MapperTypes.Items.keySpec(partitionKeyTypeRefs))
            keySpecInstantiation(partitionKeyProps)
            newline()

            if (sortKeyProps.isNotEmpty()) {
                writeInline("override val sortKey: #T = ", MapperTypes.Items.keySpec(sortKeyTypeRefs))
                keySpecInstantiation(sortKeyProps)
                newline()
            }

            // Handle TTL annotations
            val ttlFields = properties.mapNotNull { prop ->
                prop.annotations
                    .singleOrNull { it.annotationType.resolve().declaration.qualifiedName?.asString() == DynamoDbTtlSeconds::class.qualifiedName }
                    ?.let { annotation ->
                        val lifetime = annotation.arguments.single().value as? Long ?: error("@DynamoDbTtlSeconds annotation argument on property ${prop.ddbName} could not be evaluated at compile time. Use a literal value like @DynamoDbTtlSeconds(3600) instead of expressions like @DynamoDbTtlSeconds(1.hours.inWholeSeconds).")
                        require(lifetime > 0) { "@DynamoDbTtlSeconds must be positive, got $lifetime seconds on property ${prop.ddbName}" }
                        prop.simpleName.getShortName() to lifetime
                    }
            }.toMap()

            // Handle Counter annotation
            val counterFields = properties.mapNotNull { prop ->
                prop.annotations
                    .singleOrNull { it.annotationType.resolve().declaration.qualifiedName?.asString() == DynamoDbCounter::class.qualifiedName }
                    ?.let {
                        // Validate that counter properties are Int or Long
                        require(prop.typeRef == Types.Kotlin.Int || prop.typeRef == Types.Kotlin.Long) {
                            "Property '${prop.name}' annotated with @DynamoDbCounter must be of type Int or Long, but was ${prop.typeRef.shortName}"
                        }
                        prop.simpleName.getShortName()
                    }
            }.toSet()

            val hasAttributes = ttlFields.isNotEmpty() || counterFields.isNotEmpty()

            if (hasAttributes) {
                if (ttlFields.isNotEmpty()) {
                    val ttlFieldsCode = ttlFields.entries.joinToString { (fieldName, lifetime) ->
                        format("#S to #LL", fieldName, lifetime)
                    }
                    write("private val ttlFields = #T(#L)", Types.Kotlin.Collections.mapOf, ttlFieldsCode)
                }

                withBlock(
                    "override val attributes: #T = #T {",
                    "}",
                    Type.from(RuntimeTypes.Core.Collections.Attributes),
                    Type.from(RuntimeTypes.Core.Collections.attributesOf),
                ) {
                    if (ttlFields.isNotEmpty()) {
                        write("#T.TtlFields to ttlFields", MapperTypes.Model.SchemaAttributes)
                    }
                    if (counterFields.isNotEmpty()) {
                        val counterFieldsCode = counterFields.joinToString { format("#S", it) }

                        write(
                            "#T.CounterFields to #T(#L)",
                            MapperTypes.Model.SchemaAttributes,
                            Types.Kotlin.Collections.setOf,
                            counterFieldsCode,
                        )
                    }
                }
            } else {
                write(
                    "override val attributes: #T = #T()",
                    Type.from(RuntimeTypes.Core.Collections.Attributes),
                    Type.from(RuntimeTypes.Core.Collections.emptyAttributes),
                )
            }
        }

        blankLine()
    }

    private fun keySpecInstantiation(keyProps: List<KSPropertyDeclaration>) {
        val first = keyProps.first()
        val rest = keyProps.drop(1)

        val firstTypeRef = when (first.typeRef) {
            Types.Kotlin.Byte -> MapperTypes.Items.KeySpecByte
            Types.Kotlin.ByteArray -> MapperTypes.Items.KeySpecByteArray
            Types.Kotlin.Int -> MapperTypes.Items.KeySpecInt
            Types.Kotlin.Long -> MapperTypes.Items.KeySpecLong
            Types.Kotlin.Short -> MapperTypes.Items.KeySpecShort
            Types.Kotlin.String -> MapperTypes.Items.KeySpecString
            else -> error("Unsupported key attribute type ${first.typeRef}")
        }

        writeInline("#T(#S)", firstTypeRef, first.ddbName)

        rest.forEach { prop ->
            val typeRef = when (prop.typeRef) {
                Types.Kotlin.Byte -> MapperTypes.Items.KeySpecThenByte
                Types.Kotlin.ByteArray -> MapperTypes.Items.KeySpecThenByteArray
                Types.Kotlin.Int -> MapperTypes.Items.KeySpecThenInt
                Types.Kotlin.Long -> MapperTypes.Items.KeySpecThenLong
                Types.Kotlin.Short -> MapperTypes.Items.KeySpecThenShort
                Types.Kotlin.String -> MapperTypes.Items.KeySpecThenString
                else -> error("Unsupported key attribute type ${prop.typeRef}")
            }

            writeInline(".#T(#S)", typeRef, prop.ddbName)
        }
    }

    private fun renderGetTable() {
        docs("Returns a reference to a table named [name] containing items representing [#T]", classType)

        val tableType = if (sortKeyProps.isEmpty()) {
            MapperTypes.Model.tablePartitionKey(classType, partitionKeyTypeRefs)
        } else {
            MapperTypes.Model.tableCompositeKey(classType, partitionKeyTypeRefs, sortKeyTypeRefs)
        }

        generatedAnnotation()
        val fnName = "get${className}Table"
        write(
            "#Lfun #T.#L(name: String): #T = #L(name, #L)",
            ctx.attributes.visibility,
            MapperTypes.DynamoDbMapper,
            fnName,
            tableType,
            "getTable",
            schemaName,
        )
    }
}

@OptIn(KspExperimental::class)
private val KSType.isUserClass: Boolean
    get() = declaration.isDynamoDbMappable

/**
 * True if this declaration is annotated with a type that is (or is itself meta-annotated with) [DynamoDbMappable].
 * This covers both nested-only types annotated directly with [DynamoDbMappable] and table items annotated with
 * [DynamoDbItem] (which is meta-annotated with [DynamoDbMappable]).
 */
@OptIn(KspExperimental::class)
internal val KSDeclaration.isDynamoDbMappable: Boolean
    get() = annotations.any { ann ->
        val decl = ann.annotationType.resolve().declaration
        decl.qualifiedName?.asString() == DynamoDbMappable::class.qualifiedName ||
            decl.isAnnotationPresent(DynamoDbMappable::class)
    }

private val KSDeclaration.isObject: Boolean
    get() = (this as? KSClassDeclaration)?.classKind == ClassKind.OBJECT

@OptIn(KspExperimental::class)
private val KSPropertyDeclaration.isPk: Boolean
    get() = isAnnotationPresent(DynamoDbPartitionKey::class)

@OptIn(KspExperimental::class)
private val KSPropertyDeclaration.isSk: Boolean
    get() = isAnnotationPresent(DynamoDbSortKey::class)

private val KSPropertyDeclaration.name: String
    get() = simpleName.getShortName()

private val KSPropertyDeclaration.typeRef: TypeRef
    get() = Type.from(type)

@OptIn(KspExperimental::class)
private val KSPropertyDeclaration.ddbName: String
    get() = getAnnotationsByType(DynamoDbAttribute::class).singleOrNull()?.name ?: name

private val KSType.isEnum: Boolean
    get() = (declaration as? KSClassDeclaration)?.classKind == ClassKind.ENUM_CLASS
