/*
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 * SPDX-License-Identifier: Apache-2.0
 */
package aws.sdk.kotlin.hll.dynamodbmapper.codegen.operations.rendering

import aws.sdk.kotlin.hll.codegen.core.CodeGenerator
import aws.sdk.kotlin.hll.codegen.model.Member
import aws.sdk.kotlin.hll.codegen.model.Structure
import aws.sdk.kotlin.hll.codegen.model.TypeVar
import aws.sdk.kotlin.hll.codegen.model.genericVars
import aws.sdk.kotlin.hll.codegen.rendering.BuilderRenderer
import aws.sdk.kotlin.hll.codegen.rendering.RenderContext
import aws.sdk.kotlin.hll.codegen.rendering.RenderOptions
import aws.sdk.kotlin.hll.codegen.rendering.Visibility
import aws.sdk.kotlin.hll.codegen.util.plus
import aws.sdk.kotlin.hll.dynamodbmapper.codegen.operations.model.DataType
import aws.sdk.kotlin.hll.dynamodbmapper.codegen.operations.model.isInherited
import aws.sdk.kotlin.hll.dynamodbmapper.codegen.operations.model.members

/**
 * Generates immutable data types from a [Structure] into an underlying [CodeGenerator]. At their simplest, these data
 * types consist of:
 * * a read-only `interface` (with a `val` field for each [Structure] member)
 * * a `private data class` that serves as the default implementation
 * * a `toBuilder` method which turns a built object into a builder
 * * a `copy` method which modifies a copy of a built object and returns the result
 * * a DSL factory function named after the generated interface for creating new instances
 *
 * This generator delegates to [BuilderRenderer] to also generate builders.
 *
 * Example of generated data type:
 *
 * ```kotlin
 * public interface FooRequest<T> {
 *     public companion object { }
 *
 *     public val id: Int
 *     public val name: String
 *     public val foo: T
 * }
 *
 * private data class FooImpl<T>(
 *     override val id: Int,
 *     override val name: String,
 *     override val foo: T,
 * ) : FooRequest<T>
 *
 * // Builder generated by BuilderRenderer
 *
 * public fun <T> FooRequest<T>.toBuilder(): FooRequestBuilder<T> = FooRequestBuilder<T>.apply {
 *     id = this@toBuilder.id
 *     name = this@toBuilder.name
 *     foo = this@toBuilder.foo
 * }
 *
 * public fun <T> FooRequest<T>.copy(block: FooRequestBuilder<T>.() -> Unit): FooRequest<T> =
 *     toBuilder.apply(block).build()
 *
 * public fun <T> FooRequest(block: FooRequestBuilder<T>.() -> Unit): FooRequest<T> =
 *     FooRequestBuilder<T>().apply(block).build()
 * ```
 *
 * ## Key type variants
 *
 * A data type may have "variants" which are specializations for different key topologies. The
 * [aws.sdk.kotlin.hll.dynamodbmapper.codegen.operations.model.MemberCodegenBehavior.MapToKeys] value indicates that
 * some [Member] needs to be mapped to key fields: a single key field for schemas without sort keys and dual key fields
 * for schemas _with_ sort keys.
 *
 * For these cases, the generated data types consist of:
 * * a read-only `sealed interface` (with a `val` field for each _non-key_ [Structure] member)
 *   * a `.PartitionKey<PK>` sub-interface with a field for partition key
 *   * a `.CompositeKey<PK, SK>` sub-interface with fields for partition key and sort key
 * * Two `private data class` variants that serve as the default implementations
 * * `toBuilder` methods which turn built objects into a builders
 * * `copy` methods which modify copies of built objects and return the results
 * * DSL factory function overloads named after the generated parent interface for creating new instances
 *
 * Example of generated data type with variants:
 *
 * ```kotlin
 * public sealed interface FooRequest<T> {
 *     public companion object { }
 *
 *     public val id: Int
 *     public val name: String
 *     public val foo: T
 *
 *     public interface PartitionKey<T, PK : KeyType> : FooRequest<T> {
 *         public val partitionKey: PK
 *     }
 *
 *     public interface CompositeKey<T, PK : KeyType, SK : KeyType> : FooRequest<T> {
 *         public val partitionKey: PK
 *         public val sortKey: SK
 *     }
 * }
 *
 * private data class UserPartitionKeyImpl<T, PK : KeyType>(
 *     override val id: Int,
 *     override val name: String,
 *     override val foo: T,
 *     override val partitionKey: PK,
 * ) : FooRequest.PartitionKey<T, PK>
 *
 * private data class UserCompositeKeyImpl<T, PK : KeyType, SK : KeyType>(
 *     override val id: Int,
 *     override val name: String,
 *     override val foo: T,
 *     override val partitionKey: PK,
 *     override val sortKey: SK,
 * ) : FooRequest.CompositeKey<T, PK, SK>
 *
 * // Builders generated by BuilderRenderer
 *
 * public fun <T> FooRequest.PartitionKey<T, PK : KeyType>.toBuilder(): FooRequestPartitionKeyBuilder<T, PK> =
 *     FooRequestPartitionKeyBuilder<T, PK>.apply {
 *         id = this@toBuilder.id
 *         name = this@toBuilder.name
 *         foo = this@toBuilder.foo
 *         partitionKey = this@toBuilder.partitionKey
 *     }
 *
 * public fun <T> FooRequest.CompositeKey<T, PK : KeyType, SK : KeyType>.toBuilder(): FooRequestCompositeKeyBuilder<T, PK, SK> =
 *     FooRequestCompositeKeyBuilder<T, PK, SK>.apply {
 *         id = this@toBuilder.id
 *         name = this@toBuilder.name
 *         foo = this@toBuilder.foo
 *         partitionKey = this@toBuilder.partitionKey
 *         sortKey = this@toBuilder.sortKey
 *     }
 *
 * public fun <T> FooRequest.PartitionKey<T, PK : KeyType>.copy(
 *     block: FooRequestPartitionKeyBuilder<T, PK>.() -> Unit,
 * ): FooRequest.PartitionKey<T, PK> = toBuilder().apply(block).build()
 *
 * public fun <T> FooRequest.CompositeKey<T, PK : KeyType, SK : KeyType>.copy(
 *     block: FooRequestCompositeKeyBuilder<T, PK, SK>.() -> Unit,
 * ): FooRequest.CompositeKey<T, PK, SK> = toBuilder().apply(block).build()
 *
 * public fun <T, PK : KeyType> FooRequest.Companion.PartitionKey(
 *     block: FooRequestPartitionKeyBuilder<T, PK>.() -> Unit,
 * ): FooRequest.PartitionKey<T, PK> = FooRequestPartitionKeyBuilder<T, PK>().apply(block).build()
 *
 * public fun <T, PK : KeyType, SK : KeyType> FooRequest.Companion.CompositeKey(
 *     block: FooRequestCompositeKeyBuilder<T, PK, SK>.() -> Unit,
 * ): FooRequest.CompositeKey<T, PK, SK> = FooRequestCompositeKeyBuilder<T, PK, SK>().apply(block).build()
 * ```
 *
 * @param ctx The active rendering context
 * @param generator The underlying generator for the context into which the data type should be written
 * @param structure The [Structure] which describes the data type for which to generate code
 */
internal class DataTypeGenerator(
    private val ctx: RenderContext,
    generator: CodeGenerator,
    private val dataType: DataType,
) : CodeGenerator by generator {
    fun generate() {
        dataType.renderInterface()
        blankLine()
        dataType.renderImpl()
    }

    private val DataType.interfaceRefWithGenerics: String
        get() = format("#L#G", interfaceStruct.type.leafName, interfaceStruct.type.genericVars())

    private fun DataType.renderInterface(scopedParentRef: String? = null) {
        val interfaceModifier = if (this is DataType.Concrete) "" else "sealed "
        val interfaceRef = this.interfaceRefWithGenerics

        writeInline("public #Linterface #L ", interfaceModifier, interfaceRef)
        scopedParentRef?.let { writeInline(": #L ", it) }
        withBlock("{", "}", interfaceModifier, interfaceStruct.type) {
            write("public companion object { }")
            blankLine()
            interfaceStruct.members {
                if (!isInherited) write("public val #L: #T", name, type)
            }

            if (this is DataType.Abstract) {
                variants.forEach { variant ->
                    blankLine()
                    variant.renderInterface(interfaceRef)
                }
            }
        }
    }

    private fun DataType.renderImpl(scopedParentRef: String? = null) {
        if (this is DataType.Concrete) {
            val generics = implStruct.type.genericVars()

            renderDataClass(generics)
            blankLine()
            renderBuilder()
            blankLine()
            renderToBuilder(generics)

            blankLine()
            withBlock(
                "public fun #1G#2T.copy(block: #3T.() -> Unit): #2T =",
                "",
                generics,
                interfaceStruct.type,
                builderStruct.type,
            ) {
                write("toBuilder().apply(block).build()")
            }

            val receiver = scopedParentRef?.let { "$it." } ?: ""

            blankLine()
            withBlock(
                "public fun #G#L#L(block: #T.() -> Unit): #T =",
                "",
                generics,
                receiver,
                interfaceStruct.type.leafName,
                builderStruct.type,
                interfaceStruct.type,
            ) {
                write("#T().apply(block).build()", builderStruct.type)
            }
        } else if (this is DataType.Abstract) {
            variants.forEach { it.renderImpl("${interfaceStruct.type.leafName}.Companion") }
        }
    }

    private fun DataType.Concrete.renderToBuilder(generics: List<TypeVar>) {
        withBlock(
            "public fun #1G#2T.toBuilder(): #3T = #3T().apply {",
            "}",
            generics,
            interfaceStruct.type,
            builderStruct.type,
        ) {
            builderStruct.members { write("#1L = this@toBuilder.#1L", name) }
        }
    }

    private fun DataType.Concrete.renderBuilder() {
        val builderCtx = ctx.copy(
            attributes = ctx.attributes + (RenderOptions.VisibilityAttribute to Visibility.PUBLIC),
        )
        BuilderRenderer(
            generator = this@DataTypeGenerator,
            builtType = interfaceStruct.type,
            implementationType = implStruct.type,
            members = builderStruct.members,
            ctx = builderCtx,
            builderNameOverride = builderStruct.type.shortName,
        ).render()
    }

    private fun DataType.Concrete.renderDataClass(generics: List<TypeVar>) {
        openBlock("private data class #L#G(", implStruct.type.shortName, generics)
        implStruct.members { write("override val #L: #T,", name, type) }
        closeBlock("): #T", interfaceStruct.type)
    }
}
