name: Setup Build
description: >
  Checkout repositories and build dependencies

runs:
  using: composite
  steps:
    - name: Checkout sources
      uses: actions/checkout@v4
      with:
        path: 'aws-sdk-kotlin'
    - name: Checkout tools
      uses: actions/checkout@v4
      with:
        path: 'aws-kotlin-repo-tools'
        repository: 'awslabs/aws-kotlin-repo-tools'
        ref: 'gh-action'
        sparse-checkout: |
          .github
    - name: Checkout smithy-kotlin
      uses: ./aws-kotlin-repo-tools/.github/actions/checkout-head
      with:
        # checkout smithy-kotlin as a sibling which will automatically make it an included build
        path: 'smithy-kotlin'
        repository: 'awslabs/smithy-kotlin'
    - name: Configure JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'corretto'
        java-version: 17
        cache: 'gradle'
    - name: Build smithy-kotlin
      shell: bash
      run: |
        echo "REPO_TOOLS=$GITHUB_WORKSPACE/aws-kotlin-repo-tools" >> "$GITHUB_ENV"
        echo "SMITHY_KOTLIN_DIR=$GITHUB_WORKSPACE/smithy-kotlin" >> "$GITHUB_ENV"
        echo "SDK_DIR=$GITHUB_WORKSPACE/aws-sdk-kotlin" >> "$GITHUB_ENV"
        pushd $SMITHY_KOTLIN_DIR
        ./gradlew assemble publishToMavenLocal
        popd
