/*
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 * SPDX-License-Identifier: Apache-2.0
 */

import aws.sdk.kotlin.dokka.TrimNavigation

plugins {
    id("org.jetbrains.dokka")
}

dokka {
    val sdkVersion: String by project
    moduleVersion.set(sdkVersion)

    val isolationMode = properties["dokka.isolationMode"]?.toString()?.lowercase() ?: "process"
    val heapSize = properties["dokka.maxHeapSize"]?.toString() ?: "16g"

    dokkaGeneratorIsolation = when (isolationMode) {
        "classloader" -> ClassLoaderIsolation { }.also { println("Configured Dokka with classloader isolation") }
        else -> ProcessIsolation {
            maxHeapSize = heapSize
        }.also { println("Configured Dokka with process isolation and maxHeapSize=${it.maxHeapSize.get()}") }
    }

    pluginsConfiguration.html {
        customStyleSheets.from(
            rootProject.file("docs/dokka-presets/css/aws-styles.css"),
        )

        customAssets.from(
            rootProject.file("docs/dokka-presets/assets/logo-icon.svg"),
            rootProject.file("docs/dokka-presets/scripts/accessibility.js"),
            rootProject.file("docs/dokka-presets/scripts/custom-navigation-loader.js"),
        )

        templatesDir.set(rootProject.file("docs/dokka-presets/templates"))

        footerMessage.set("© ${java.time.LocalDate.now().year}, Amazon Web Services, Inc. or its affiliates. All rights reserved.")
        separateInheritedMembers.set(true)
    }

    dokkaSourceSets.configureEach {
        // Only configure samples on `commonMain`.
        // Fixes compiler warnings: "Source sets 'common' and 'desktop' have the common sample roots. In Dokka K2 it will be an error."
        if (name == "commonMain") {
            samples.from(project.file("samples").path, project.file("generated-src/samples").path)
        }

        // Each module can include their own top-level module documentation in one or more included Markdown files,
        // each of which must begin with `# Module <module-name>` where <module-name> is the literal name of the
        // Gradle module. See https://kotlinlang.org/docs/dokka-module-and-package-docs.html for more details.
        // Files are processed in order, so list them in the desired display order.
        val includeFiles = listOf(
            "OVERVIEW.md", // Auto-generated by ModuleDocumentationIntegration
            "DOCS.md", // Hand-written docs explaining a module in greater detail
            "EXAMPLES.md", // Generated by `kat` tool, code examples
            "OPERATIONS.md", // Generated by `kat` tool, all service operations
        ).mapNotNull { project.file(it).takeIf { it.exists() } }
        includes.from(includeFiles)
    }

    // Configure Dokka to link to smithy-kotlin types
    dokkaSourceSets.configureEach {
        externalDocumentationLinks {
            create("smithy-kotlin") {
                url("https://docs.aws.amazon.com/smithy-kotlin/api/latest")
            }
        }
    }
}

dependencies {
    dokkaPlugin(project(":dokka-aws"))
}

val trimNavigationTask = tasks.register<TrimNavigation>("trimNavigationFiles") {
    sourceDirectory.set(layout.buildDirectory.get().dir("dokka/html"))
}

tasks.dokkaGenerate {
    finalizedBy(trimNavigationTask)
}
