/*
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 * SPDX-License-Identifier: Apache-2.0
 */
package aws.sdk.kotlin.hll.dynamodbmapper.items

import aws.sdk.kotlin.hll.dynamodbmapper.model.Item
import aws.sdk.kotlin.hll.mapping.core.converters.Converter

/**
 * Defines the logic for converting between objects and DynamoDB items
 * @param T The type of objects which will be converted
 */
public typealias ItemConverter<T> = Converter<T, Item>

/**
 * A sentinel value for indicating that an [ItemConverter] should be automatically generated by
 * dynamodb-mapper-schema-generator-plugin. This object _cannot_ be used to convert items directly and will throw
 * exceptions when calling [convertLeft] or [convertRight].
 */
public object AutoGeneratedConverter : ItemConverter<Any?> {
    private const val MESSAGE = "This converter is a sentinel value and cannot be used directly to convert items"
    override fun convertLeft(from: Item): Nothing = error(MESSAGE)
    override fun convertRight(from: Any?): Nothing = error(MESSAGE)
}
