name: API Docs

on: # TODO: determine best event hook (release, etc)
  workflow_dispatch:

env:
  DOC_BRANCH_NAME: api-docs # the branch from which github pages content is sourced
  PUBLISH_ARTIFACT: true # toggle publishing all docs as artifact

jobs:
  smithy-kotlin-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
        with:
          repository: awslabs/smithy-kotlin # todo sync versions
      - name: Build upstream docs
        id: smithy-kotlin-build
        run: |
          ./gradlew dokkaHtmlMultiModule
          mkdir smithy-kotlin-docs
          mv build/dokka/htmlMultiModule/* smithy-kotlin-docs/
      - name: Upload Smithy-Kotlin Doc Artifact
        uses: actions/upload-artifact@v2
        with:
          name: smithy-kotlin-docs
          path: smithy-kotlin-docs

  api-doc-gen-parallel:
    runs-on: ubuntu-latest
    needs: smithy-kotlin-docs
    strategy:
      matrix:
        service-prefix: [ a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z ]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Download smithy-kotlin artifacts
        uses: actions/download-artifact@v2
        with:
          name: smithy-kotlin-docs
          path: smithy-kotlin-docs
      - name: Generate API Docs
        id: gen-docs
        run: |
          # Do not generate SDKs for the following unsupported SDKs
          excluded_services=("transcribestreaming" "timestreamwrite" "timestreamquery")

          # Resource mgmt optimization for Dokka
          printf "\norg.gradle.daemon=false" >> gradle.properties

          # do not execute following loop if no files w prefix
          shopt -s nullglob

          # configure path to smithy-kotlin's package-list
          smithy_kotlin_package_list_path="$(pwd)/smithy-kotlin-docs/package-list"

          # Iterate over service models, extract the name and codegen each SDK discretely
          for aws_model_file in codegen/sdk/aws-models/${{ matrix.service-prefix }}*.json
          do
            # delete src for any previously generated SDK
            git clean -dfx services

            docs_generated=true
            MODEL_FILENAME=${aws_model_file##*/}    # Extract the filename from the path
            SERVICE_NAME=$(echo "$MODEL_FILENAME" | cut -d. -f1 ) # Extract the service name from the filename
            excluded=$(echo "${excluded_services[@]}" | grep -ow "$SERVICE_NAME" | wc -w)
            if [[ $excluded == 0 ]]; then
              echo "Building docs for $SERVICE_NAME"

              ./gradlew -Paws.services=+$SERVICE_NAME :codegen:sdk:bootstrap  # generate SDK

              # Retry due to transient network failures during doc generation
              # https://unix.stackexchange.com/a/82602
              n=0
              until [ "$n" -ge 5 ]
              do
                 ./gradlew --no-parallel -PdokkaOutSubDir=$SERVICE_NAME -PsmithyKotlinPackageListUrl=file://$smithy_kotlin_package_list_path dokkaHtmlMultiModule && break
                 n=$((n+1))
                 sleep 15
              done
            else # SDK was excluded
              echo "Ignoring excluded service $SERVICE_NAME"
              docs_generated=false
            fi
          done
          echo ::set-output name=docs-generated::"$docs_generated"
      - name: Compress Docs
        if: steps.gen-docs.outputs.docs-generated == 'true'
        run: |
          tar cJf api-docs-${{ matrix.service-prefix }}.tar.xz build/dokka/*
      - name: Upload Artifact
        if: steps.gen-docs.outputs.docs-generated == 'true'
        uses: actions/upload-artifact@v2
        with:
          name: api-docs-${{ matrix.service-prefix }}
          path: api-docs-${{ matrix.service-prefix }}.tar.xz
          retention-days: 1 # These intra-workflow artifacts are not needed after final docs generated

  # Download all artifacts from previous job, extract them to common dir, add top-level index and push to ghpages branch
  combine-docs:
    needs: api-doc-gen-parallel
    runs-on: ubuntu-latest
    steps:
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v2
      - name: Consolidate Service Docs
        run: |
          mkdir target

          for suffix in {a..z}
          do
            ARCHIVE="api-docs-$suffix/api-docs-$suffix.tar.xz"

            if [ -f "$ARCHIVE" ]; then
              tar xf "$ARCHIVE"
              mv build/dokka/* target/
              rm -Rf build
            else
              echo "Did not find archive for $ARCHIVE"
            fi
          done
      - name: Add smithy-kotlin docs
        run: |
          mv smithy-kotlin-docs target/
      - name: Generate Top Level Index
        run: |
          INDEX_FILE=target/index.html

          # Generate page header
          echo "<!DOCTYPE html>" >> $INDEX_FILE
          echo "<html>" >> $INDEX_FILE
          echo "" >> $INDEX_FILE
          echo "<head>" >> $INDEX_FILE
          echo "    <meta name='viewport' content='width=device-width, initial-scale=1' charset='UTF-8'>" >> $INDEX_FILE
          echo "    <title>AWS Services</title>" >> $INDEX_FILE
          echo "    <link href='images/logo-icon.svg' rel='icon' type='image/svg'>" >> $INDEX_FILE
          echo "    <link href='styles/style.css' rel='Stylesheet'>" >> $INDEX_FILE
          echo "    <link href='styles/logo-styles.css' rel='Stylesheet'>" >> $INDEX_FILE
          echo "    <link href='styles/jetbrains-mono.css' rel='Stylesheet'>" >> $INDEX_FILE
          echo "    <link href='styles/main.css' rel='Stylesheet'>" >> $INDEX_FILE
          echo "    <link href='images/logo-icon.svg'>" >> $INDEX_FILE
          echo "    <link href='images/aws_logo_white_59x35.png'>" >> $INDEX_FILE
          echo "    <link href='styles/logo-styles.css' rel='Stylesheet'>" >> $INDEX_FILE
          echo "    <link href='styles/multimodule.css' rel='Stylesheet'>" >> $INDEX_FILE
          echo "</head>" >> $INDEX_FILE
          echo "" >> $INDEX_FILE
          echo "<body>" >> $INDEX_FILE
          echo "    <div id='container'>" >> $INDEX_FILE
          echo "        <div id='leftColumn'>" >> $INDEX_FILE
          echo "            <div id='logo'></div>" >> $INDEX_FILE
          echo "        </div>" >> $INDEX_FILE
          echo "        <div id='main' class='main-content'>" >> $INDEX_FILE
          echo "            <h2>AWS SDK for Kotlin API Docs</h2>" >> $INDEX_FILE
          echo "            <div class='table'>" >> $INDEX_FILE

          # Generate list of services
          for aws_service_dir in target/*
          do
            if [[ "$aws_service_dir" !=  "target/index.html" && "$aws_service_dir" !=  "target/smithy-kotlin-docs" ]]; then # no self reference
              SERVICE_NAME=${aws_service_dir##*/}    # Extract the filename from the path

              echo "    <div class='table-row'>" >> $INDEX_FILE
              echo "        <div class='main-subrow '>" >> $INDEX_FILE
              echo "            <div class='w-100'>" >> $INDEX_FILE
              echo "                <span class='inline-flex'>" >> $INDEX_FILE
              echo "                    <a href='$SERVICE_NAME/index.html'>$SERVICE_NAME</a>" >> $INDEX_FILE
              echo "                </span>" >> $INDEX_FILE
              echo "            </div>" >> $INDEX_FILE
              echo "        </div>" >> $INDEX_FILE
              echo "    </div>" >> $INDEX_FILE

            fi
          done

          # Generate page footer
          echo "          </div>" >> $INDEX_FILE
          echo "        </div>" >> $INDEX_FILE
          echo "</body>" >> $INDEX_FILE
          echo "</html>" >> $INDEX_FILE
      - name: Copy Styles to root # Take the styles and images from a service into the root for consistent styling
        run: |
          FIRST_SERVICE=$(find target/ -maxdepth 1 -mindepth 1 -type d | head -n 1)
          cp -r $FIRST_SERVICE/styles $FIRST_SERVICE/images target/
      - name: Prepare Release
        id: prep-release
        if: env.PUBLISH_ARTIFACT == 'true'
        run: |
          mv target kotlin-sdk-api-docs
          zip -r kotlin-sdk-api-docs.zip kotlin-sdk-api-docs/
          echo "::set-output name=timestamp::$(date +'%s')"
      - name: Release
        if: env.PUBLISH_ARTIFACT == 'true'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: api-docs-${{ steps.prep-release.outputs.timestamp }}
          files: |
            kotlin-sdk-api-docs.zip