name: Changelog verification

permissions:
  id-token: write
  contents: read

on:
  pull_request:
    types: [ opened, synchronize, reopened, labeled, unlabeled ]
    branches:
      - main
      - '*-main'

jobs:
  changelog-verification:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::886436966712:role/Admin
          aws-region: us-west-2

      - name: Verify changelog
        uses: aws/aws-kotlin-repo-tools/.github/actions/changelog-verification@main