name: CI

on:
  pull_request:
  workflow_dispatch:

# Allow one instance of this workflow per pull request, and cancel older runs when new changes are pushed
concurrency:
  group: ci-pr-${{ github.ref }}
  cancel-in-progress: true

env:
  RUN: ${{ github.run_id }}-${{ github.run_number }}
  GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dkotlin.incremental=false"

jobs:
  jvm:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # we build with a specific JDK version but source/target compatibility should ensure the jar is usable by
        # the target versions we want to support
        java-version:
          - 8
          - 11
          - 17
          - 21
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          path: 'aws-sdk-kotlin'
      - name: Setup Build
        uses: ./aws-sdk-kotlin/.github/actions/setup-build
      - name: Configure Gradle
        uses: awslabs/aws-kotlin-repo-tools/.github/actions/configure-gradle@main
        with:
          working-directory: ./aws-sdk-kotlin
      - name: Test
        working-directory: ./aws-sdk-kotlin
        shell: bash
        run: |
          pwd
          ls -lsa
          ./gradlew -Ptest.java.version=${{ matrix.java-version }} jvmTest --stacktrace
      - name: Save Test Reports
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: '**/build/reports'

  all-platforms:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          path: 'aws-sdk-kotlin'

      - name: Setup Build
        uses: ./aws-sdk-kotlin/.github/actions/setup-build

      # FIXME Re-enable Kotlin/Native builds when artifacts are available
      - name: Disable Kotlin/Native builds
        shell: bash
        run: |
          echo "Echo my echoes"
          echo "aws-sdk-kotlin"
          echo "" >> ./aws-sdk-kotlin/gradle.properties
          echo "aws.kotlin.native=false" >> ./aws-sdk-kotlin/gradle.properties
          echo "smithy-kotlin"
          echo "" >> ./smithy-kotlin/gradle.properties
          echo "aws.kotlin.native=false" >> ./smithy-kotlin/gradle.properties
          echo "aws-crt-kotlin"
          echo "" >> ./aws-crt-kotlin/gradle.properties
          echo "aws.kotlin.native=false" >> ./aws-crt-kotlin/gradle.properties

      - name: Debug smithy-kotlin
        shell: bash
        working-directory: smithy-kotlin
        run: |
          echo "Debugging smithy-kotlin"
          echo "ls:"
          ls
          echo "gradle.properties"
          cat gradle.properties
          echo "git branch"
          git branch

      - name: Debug aws-crt-kotlin
        shell: bash
        working-directory: aws-crt-kotlin
        run: |
          echo "Debugging aws-crt-kotlin"
          echo "ls:"
          ls
          echo "gradle.properties"
          cat gradle.properties
          echo "git branch"
          git branch
          echo "WithCrt"
          cat aws-crt-kotlin/common/src/aws/sdk/kotlin/crt/WithCrt.kt
          

      - name: Configure Gradle - smithy-kotlin
        uses: awslabs/aws-kotlin-repo-tools/.github/actions/configure-gradle@main
        with:
          working-directory: ./smithy-kotlin

      - name: Build smithy-kotlin
        working-directory: ./smithy-kotlin
        shell: bash
        run: |
          # protocol tests require everything is published
          pwd
          ./gradlew -Paws.kotlin.native=false --parallel assemble 
          ./gradlew -Paws.kotlin.native=false publishToMavenLocal

      - name: Configure Gradle aws-sdk-kotlin
        uses: awslabs/aws-kotlin-repo-tools/.github/actions/configure-gradle@main
        with:
          working-directory: ./aws-sdk-kotlin

      - name: Test
        working-directory: ./aws-sdk-kotlin
        shell: bash
        run: |
          pwd
          ./gradlew -Paws.kotlin.native=false :build-support:test
          ./gradlew -Paws.kotlin.native=false publishToMavenLocal
          ./gradlew -Paws.kotlin.native=false apiCheck
          ./gradlew -Paws.kotlin.native=false test jvmTest
          ./gradlew -Paws.kotlin.native=false testAllProtocols

      - name: Save Test Reports
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: '**/build/reports'
