name: CI

on:
  pull_request:
  workflow_dispatch:

# Allow one instance of this workflow per pull request, and cancel older runs when new changes are pushed
concurrency:
  group: ci-pr-${{ github.ref }}
  cancel-in-progress: true

env:
  RUN: ${{ github.run_id }}-${{ github.run_number }}
  GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dkotlin.incremental=false"

jobs:
  jvm:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java-version:
          - 8
          - 11
          - 17
          - 19
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          path: 'aws-sdk-kotlin'
      - name: Setup Build
        uses: ./aws-sdk-kotlin/.github/actions/setup-build
      - name: Test
        working-directory: ./aws-sdk-kotlin
        shell: bash
        run: |
          pwd
          ls -lsa
          ./gradlew -Djava.test.version=${{ matrix.java-version }} jvmTest --stacktrace

  all-platforms:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-2019 ]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          path: 'aws-sdk-kotlin'
      - name: Setup Build
        uses: ./aws-sdk-kotlin/.github/actions/setup-build
      - name: Test
        working-directory: ./aws-sdk-kotlin
        shell: bash
        run: |
          pwd
          # protocol tests require everything is published
          ./gradlew publishToMavenLocal
          ./gradlew apiCheck
          ./gradlew test allTests
          ./gradlew testAllProtocols