name: CI

on:
  push:
    branches:
      - '*'
      - '!main'
  pull_request:
    branches:
      - 'main'

env:
  BUILDER_VERSION: fix-dependency-steps
  BUILDER_SOURCE: channels
  BUILDER_HOST: https://d19elf31gohf1l.cloudfront.net
  PACKAGE_NAME: aws-sdk-kotlin
  LINUX_BASE_IMAGE: ubuntu-16-x64
  RUN: ${{ github.run_id }}-${{ github.run_number }}

jobs:
  linux-compat:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - manylinux2014-x64
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout sources
      uses: actions/checkout@v2
    - name: Configure CI Credentials
      # configure a git credentials helper for checking out private dependencies using crt-builder
      run: |
        git config --local credential.https://github.com/awslabs.helper "./scripts/git-ci-cred-helper.py"
        cat ./git/config
    - name: Build and Test ${{ env.PACKAGE_NAME }}
      env:
        CI_USER: ${{ secrets.CI_USER}}
        CI_ACCESS_TOKEN: ${{ secrets.CI_ACCESS_TOKEN }}
      run: |
        python3 -c "from urllib.request import urlretrieve; urlretrieve('${{ env.BUILDER_HOST }}/${{ env.BUILDER_SOURCE }}/${{ env.BUILDER_VERSION }}/builder.pyz?run=${{ env.RUN }}', 'builder')"
        chmod a+x builder
        ./builder build -p ${{ env.PACKAGE_NAME }}
