name: API Docs Test

on:
  workflow_dispatch:
    inputs:
      release-tag:
          description: The aws-sdk-kotlin release tag
          required: true
  release:
    types: [published]

jobs:
  smithy-kotlin-docs:
    runs-on: ubuntu-latest
    outputs:
      source-ref: ${{ steps.source-ref.outputs.build_ref }}
    steps:
      - name: Consolidate source ref
        id: source-ref
        run: |
          set -x
          if [ -z "${{ github.event.inputs.release-tag }}" ]; then
            echo ::set-output name=build_ref::"$GITHUB_REF"
          else
            echo ::set-output name=build_ref::"${{ github.event.inputs.release-tag }}"
          fi

  # Download all artifacts from previous job, extract them to common dir, add top-level index and push to ghpages branch
  combine-docs:
    needs: [ smithy-kotlin-docs ]
    runs-on: ubuntu-latest
    steps:
      - name: Prepare Release
        id: prep-release
        run: |
          set -x
          echo ${{ needs.smithy-kotlin-docs.outputs.build_ref }}

  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
      - id: step1
        run: echo "::set-output name=test::hello"
      - id: step2
        run: echo "::set-output name=test::world"
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: echo ${{needs.job1.outputs.output1}} ${{needs.job1.outputs.output2}}