name: Kat Verification

on:
  pull_request:

# Allow one instance of this workflow per pull request, and cancel older runs when new changes are pushed
concurrency:
  group: ci-pr-${{ github.ref }}
  cancel-in-progress: true

env:
  RUN: ${{ github.run_id }}-${{ github.run_number }}
  GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dkotlin.incremental=false"

jobs:
  verify-transform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          path: 'aws-sdk-kotlin'
      - name: Setup Build
        uses: ./aws-sdk-kotlin/.github/actions/setup-build
      - name: Setup kat
        uses: ./aws-sdk-kotlin/.github/actions/setup-kat
      - name: Verify
        working-directory: ./aws-sdk-kotlin
        shell: bash
        run: |
          pwd
          ls -lsa
          ./gradlew build
          ./gradlew publishAllPublicationsToTestLocalRepository
          kat brazil transform -i ./build/m2 -o ./transformed -t .brazil.json -v live -m ./codegen/sdk/packages.json