name: Lint

on:
  push:
    branches:
      - '*'
      - '!main'
      - '!*.main'
  pull_request:
    branches:
      - main
      - '*-main'
  workflow_dispatch:

env:
  PACKAGE_NAME: aws-sdk-kotlin

jobs:
  ktlint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v4
      with:
        path: 'aws-sdk-kotlin'
    - name: Configure Gradle
      uses: ./aws-sdk-kotlin/.github/actions/custom-gradle-distribution-url
    - name: Lint ${{ env.PACKAGE_NAME }}
      working-directory: ./aws-sdk-kotlin
      run: |
        ./gradlew ktlint
