name: Lint

on:
  push:
    branches:
      - '*'
      - '!main'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  PACKAGE_NAME: aws-sdk-kotlin

jobs:
  ktlint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v4
    - name: Lint ${{ env.PACKAGE_NAME }}
      run: |
        ./gradlew ktlint
