name: Lint

on:
  push:
    branches:
      - '*'
      - '!main'
      - '!*.main'
  pull_request:
    branches:
      - main
      - '*-main'
  workflow_dispatch:

env:
  PACKAGE_NAME: aws-sdk-kotlin

jobs:
  ktlint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v4
      with:
        path: 'aws-sdk-kotlin'
    - name: Configure Gradle
      run: |
        # Keep gradle version in sync with aws-sdk-kotlin/gradle/wrapper/gradle-wrapper.properties
        gradle wrapper --gradle-distribution-url https://d2pjps8lqszrgq.cloudfront.net/gradle-8.12-bin.zip
    - name: Lint ${{ env.PACKAGE_NAME }}
      working-directory: ./aws-sdk-kotlin
      run: |
        ./gradlew ktlint
