name: Lint

on:
  push:
    branches:
      - '*'
      - '!main'

env:
  PACKAGE_NAME: aws-sdk-kotlin

jobs:
  ktlint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout ${{ env.PACKAGE_NAME }} sources
      uses: actions/checkout@v2
      with:
        path: aws-sdk-kotlin
    - name: Determine smithy-kotlin branch
      id: determine_smithy_branch
      run: |
        BRANCH=${GITHUB_REF#refs/heads}
        if git ls-remote --exit-code --heads git@github.com:awslabs/smithy-kotlin ${BRANCH}; then
          echo "::set-output name=branch::${BRANCH}"
        else
          echo "::set-output name=branch::master"
        fi
    - name: Checkout smithy-kotlin sources
      uses: actions/checkout@v2
      with:
        repository: awslabs/smithy-kotlin
        ref: ${{ steps.determine_smithy_branch.outputs.branch }}
        path: smithy-kotlin
    - name: Lint ${{ env.PACKAGE_NAME }}
      working-directory: aws-sdk-kotlin
      run: |
        ./gradlew ktlint
