name: Release readiness (snapshot dependency)
description: >
  Makes sure that we aren't relying on SNAPSHOT/dev versions of smithy-kotlin before merging
  otherwise we could forget because the rest of CI is masking it.

on:
  pull_request:
    branches: [ main ]

jobs:
  release-readiness:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          path: 'aws-sdk-kotlin'

      - name: Configure Gradle
        uses: awslabs/aws-kotlin-repo-tools/.github/actions/configure-gradle@main
        with:
          working-directory: ./aws-sdk-kotlin

      - name: Build SDK
        working-directory: ./aws-sdk-kotlin
        run: ./gradlew test jvmTest

      - name: Build SDK client
        working-directory: ./aws-sdk-kotlin
        run: |
          ./gradlew -Paws.kotlin.native=false -Paws.services=s3 bootstrap
          ./gradlew -Paws.kotlin.native=false build

      - name: Checkout smithy-kotlin
        uses: awslabs/aws-kotlin-repo-tools/.github/actions/checkout-head@main
        with:
          path: 'smithy-kotlin'
          repository: 'smithy-lang/smithy-kotlin'

      # TODO: Change grep pattern when we decouple runtime and codegen releases
      - name: Check for smithy-kotlin unreleased changes
        run: |
          cd aws-sdk-kotlin
          SDK_BRANCH=$(git branch --show-current)
          
          cd ../smithy-kotlin
          SMITHY_BRANCH=$(git branch --show-current)
          
          if [ "$SDK_BRANCH" = "$SMITHY_BRANCH" ]; then
            cd ../aws-sdk-kotlin
            git diff origin/main -- gradle/libs.versions.toml | grep -E "smithy-kotlin-runtime-version|smithy-kotlin-codegen-version"
            export SMITHY_KOTLIN_VERSION_BUMP=$($?)
            
            if [ "$SMITHY_KOTLIN_VERSION_BUMP" != 0 ]; then
              exit 1
            fi
          fi

      - name: Emit error message
        if: ${{ failure() }}
        run: |
          echo "::error ::Did you forget to release smithy-kotlin and bump the dependency version?"
          exit 1
