name: Release readiness (snapshot dependency)

# Makes sure that we aren't relying on SNAPSHOT/dev versions of smithy-kotlin before merging
# Otherwise we could forget because the rest of CI is masking it

on:
  pull_request:
    branches: [ main ]

jobs:
  release-readiness:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Configure Gradle
        uses: awslabs/aws-kotlin-repo-tools/.github/actions/configure-gradle@main

      - name: Build SDK
        run: ./gradlew test jvmTest

      - name: Build SDK client
        run: |
          ./gradlew -Paws.kotlin.native=false -Paws.services=s3 bootstrap
          ./gradlew -Paws.kotlin.native=false build

      - name: Emit error message
        if: ${{ failure() }}
        run: |
          echo "::error ::Build failed. Did you forget to release smithy-kotlin and bump the dependency version?"
          exit 1
