name: Sync Mirror

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  git-sync:
    if: github.repository == 'awslabs/aws-sdk-kotlin'
    runs-on: ubuntu-latest
    steps:
      - name: git-sync
        uses: wei/git-sync@v3
        with:
          source_repo: "https://${{ secrets.CI_USER }}:${{ secrets.CI_USER_PAT }}@github.com/awslabs/aws-sdk-kotlin.git"
          source_branch: "main"
          destination_repo: "https://${{ secrets.CI_USER }}:${{ secrets.CI_USER_PAT }}@github.com/${{ secrets.GIT_SYNC_DESTINATION_REPO }}.git"
          destination_branch: "main"