name: Update release manual

on:
  workflow_dispatch:
    inputs:
      commit_message:
        description: |
          The merge commit message to use for non fast-forward merges.
        required: false
        type: string
      dry_run:
        description: Dry runs will only attempt to merge but the result will not be pushed to the release branch
        required: true
        type: boolean
        default: true

concurrency:
  group: release-manual-${{ github.ref }}
  cancel-in-progress: true

# TODO - GH token

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Update release branch
        uses: ./aws-sdk-kotlin/.github/actions/update-release
        with:
         commit_message: ${{ inputs.commit_message }}
         dry_run: ${{ inputs.dry_run }}
